# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't chang, 

Vagrant.configure("2") do |config|


	config.vm.box = "centos/7"
	config.vm.network "private_network", ip: "192.168.33.10"

	config.vm.provision :shell, :privileged => true, :path => "installation_scripts/pre_install.sh"

	config.vm.provision "file", source: "support_files/rundeck-config.properties", destination: "/etc/rundeck/"

	config.vm.provision :shell, :privileged => true, :path => "installation_scripts/post_install.sh"

end




