# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't chang,

Vagrant.configure("2") do |config|

	RDIP="192.168.50.10"
	config.vm.box = "centos/7"

  config.vm.network :private_network, ip: "#{RDIP}"

	# config.vm.network :public_network
	# config.vm.network "private_network", ip: "192.168.33.10"
end
